version: 1.0.{build}
environment:
  access_token:
    secure: H8F1UMqC4QixM9NbnHewuineXTu860e3WhkpgMzui6xQmCv2qyXd4BDonVrrW5Iv
  matrix:
  - PYVER: 27
    BITTNESS: 32
  - PYVER: 34
    BITTNESS: 32
  - PYVER: 27
    BITTNESS: 64
  - PYVER: 34
    BITTNESS: 64
build_script:
- ps: >-
    iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/matham/packaging/master/check_error.ps1'))

    cd "$env:APPVEYOR_BUILD_FOLDER"

    $env:PYTHONPATH = "$env:APPVEYOR_BUILD_FOLDER;$env:PYTHONPATH"

    if ($env:BITTNESS -eq "64") {
      $PYTHON_ROOT = "C:\Python$env:PYVER-x64"
    } else {
      $PYTHON_ROOT = "C:\Python$env:PYVER"
    }

    $env:PATH = "$PYTHON_ROOT;$PYTHON_ROOT\Scripts;$env:PATH;C:\Program Files\7-Zip"

    python -c "import sys;print('Python version is {}'.format(sys.version))"

    Check-Error

    $env:USE_SDL2 = 1

    python -c "with open(r'$PYTHON_ROOT\Lib\distutils\distutils.cfg', 'wb') as fh: fh.write(b'[build]\ncompiler = mingw32\n')"

    Check-Error

    python -m pip install --upgrade pip wheel nose setuptools

    Check-Error

    pip install -i https://pypi.anaconda.org/carlkl/simple mingwpy

    Check-Error

    pip install mock pypiwin32 psutil six https://github.com/pyinstaller/pyinstaller/archive/develop.zip numpy nixio cython pygments docutils nose kivy_deps.glew_dev kivy_deps.glew kivy_deps.sdl2_dev kivy_deps.sdl2

    Check-Error

    python -m pip install https://github.com/kivy/kivy/archive/master.zip

    Check-Error

    python -m pip install pyflycap2 ffpyplayer https://github.com/matham/cplcom/archive/master.zip

    Check-Error

    garden install filebrowser --kivy

    Check-Error

    garden install graph --kivy

    Check-Error

    garden install collider --kivy

    Check-Error

    cd $PYTHON_ROOT\Lib\site-packages\kivy\garden\collider

    python setup.py build_ext --inplace

    cd "$env:APPVEYOR_BUILD_FOLDER"

    python -m pip install -e .

    Check-Error

    mkdir deploy

    Check-Error

    if ($env:BITTNESS -eq "64" -and $env:PYVER -eq "34") {
      python setup.py sdist -d "deploy"
      Check-Error
    }

artifacts:
- path: deploy\*
  name: wheels
on_success:
- ps: >-
    if ($env:BITTNESS -eq "64" -and $env:PYVER -eq "27") {
        iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/matham/packaging/master/cpl_appveyor_gh_docs.ps1'))
    }
